*** Settings ***
Documentation     Resource file to manage all test data variables used in the project
...    
*** Variables ***
${user name}           user002    #Value to be entered in username field
${password}      userPassw0rd    #Value to be entered in password field
${first name}        userFirstName    #Value to be entered in first name field
${family name}        userFamilyName    #Value to be entered in family field
${phone}        100200300    #Value to be entered in phone field
${invalid username}    WrongName    #Value to be entered username field in login screen
${invalid userpassword}    WrongPassword    #Value to be entered password field in login screen